PUT http://localhost:3001/api/products/61747cb701d7f158c9565d96
Content-Type: application/json
Authorization: Bearer "TOKEN"

{
    "nameProduct": "suetaaaaaa",
    "price": 20000,
    "url": "www.algo2.com"
}